version: '3'
services:
  cs-lab-typing:
    build:
      context: .
      args:
        - DATABASE_URL
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env.docker
    depends_on:
      - db
    
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env.docker
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_vol:
