version: '3'
services:
  cs-lab-typing:
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      - BASE_URL=https://beta-lab.sornchaithedev.com/api
      - NEXTAUTH_URL=https://beta-lab.sornchaithedev.com
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}  
