version: '3'
services:
  cs-lab-typing:
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      - BASE_URL: cs-lab-typing/api
      - NEXTAUTH_URL: cs-lab-typing
      - NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      - DATABASE_URL: ${DATABASE_URL}
  db:
    image: postgres:latest
    restart : always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol:
