services:
  cs-lab-typing:
    build:
      context: .
    environment:
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - DATABASE_URL
    ports:
      - 3000:3000
    restart: always
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_vol:
