version: '3'
services:
  cs-lab-typing:
    build:
      context: .
    environment:
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - DATABASE_URL
    ports:
      - 3000:3000
    restart: always
