version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /app
    ports:
      - "3000:3000"
    image: cs-lab-typing
    env_file:
      - .env
    